#if !canImport(ObjectiveC)
import XCTest

extension CLImateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CLImateTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CLImateTests.__allTests__CLImateTests),
    ]
}
#endif
